app/accounts/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views

from accounts import views



urlpatterns = [
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('register/quest/', views.GuestFormView.as_view(), name='quest_register'),
    path('registration/', views.RegisterFormView.as_view(), name='registration'),
    path('logout/', views.logout_view, name='logout'),

    path('account/', views.AccountHomeView.as_view(), name='account'),

    path('email/confirm/<key>/', views.AccountEmailActivateView.as_view(), name='email-activate'),



]

app_name = 'accounts'



urlpatterns = format_suffix_patterns(urlpatterns)

app/landing/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from landing import views


urlpatterns = [
    path('', views.HomeLandingView.as_view(), name='home_landing'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),


]

app_name = 'landing'



urlpatterns = format_suffix_patterns(urlpatterns)

app/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace="todo")),
    path('', include('orders.urls', namespace="orders")),
    path('', include('products.urls', namespace="products")),
    path('', include('landing.urls', namespace="landing")),
    path('', include('parsersapi.urls', namespace="parsersapi")),
    path('', include('search.urls', namespace="search")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('billing.urls', namespace="billing")),
    path('', include('marketing.urls', namespace="marketing")),
    path('', include('analytics.urls', namespace="analytics")),

    # path('auth/social', auth_social.home, name="auth-social"),

    path('auth/social/', include('social_django.urls', namespace="social")),

    # path('', include('django.contrib.auth.urls', namespace='auth')),

    # url('', include('django.contrib.auth.urls', namespace='auth')),
    # url('', include('social.apps.django_app.urls', namespace='social')),

    path('accounts/password/change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password/change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # path('', views.index, name='home'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/todo/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from todo import views



urlpatterns = [
    path('dashboard/', views.ProjectListView.as_view(), name='dashboard'),
    path('project-create/', views.ProjectCreate.as_view(), name='project_create'),
    # projec/2/delete/
    path('project/<int:pk>/delete/', views.ProjecDelete.as_view(), name='project_delete'),
    path('todo/<int:pk>/delete/', views.TodoDelete.as_view(), name='todo_delete'),
    # projec/2/update/
    path('project/<int:pk>/update/', views.ProjecUpdate.as_view(), name='project_update'),
    path('todo/<int:pk>/update/', views.TodoUpdate.as_view(), name='todo_update'),
    path('todo/API/', views.TodoListAPI.as_view(), name='todo_api'),
    path('todo/completed/', views.CompletedListView.as_view(), name='todo_completed'),


]

app_name = 'todo'



urlpatterns = format_suffix_patterns(urlpatterns)

app/todo/models.py
from django.core.files import File
import os
import urllib
from django.urls import reverse
from django.conf import settings
from django.db import models
from django.utils import timezone

from myproject.utils import unique_slug_generator, get_filename
from django.db.models.signals import pre_save, post_save

User  = settings.AUTH_USER_MODEL


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                .filter(status='published')



class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        ('private', 'Private'),
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    author = models.CharField(max_length=170)
    body = models.TextField()
    photo = models.ImageField(upload_to='posts/%Y/%m/', blank=True, null=True, default=None)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        #return "/products/{slug}/".format(slug=self.slug)
        return reverse("parsersapi:post_detail", kwargs={"slug": self.slug})



def post_pre_save_receiver(sender, instance, *args, **kwargs):

    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(post_pre_save_receiver, sender=Post)


class Project(models.Model):
    title = models.CharField(max_length=250)
    color = models.TextField()

    objects = models.Manager()

    def __str__(self):
        return self.title


class Todo(models.Model):
    PRIORIT_CHOICES = (
        ('high', 'High Priority'),
        ('medium', 'Medium Priority'),
        ('low', 'Low Priority'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='todos')
    title = models.CharField(max_length=250)
    todo_priority = models.CharField(max_length=10, choices=PRIORIT_CHOICES, default='high')
    date_todo = models.DateField()
    completed_tasks = models.BooleanField(default=False)
    album_logo = models.FileField()

    objects = models.Manager()

    def __str__(self):
        return  self.title

app/todo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import inlineformset_factory
from .models import Project, Todo

import django_filters


class TodoFilter(django_filters.FilterSet):

    date = django_filters.DateFilter(name='date_todo', lookup_expr='gte')
    end_date = django_filters.DateFilter(name='date_todo', lookup_expr='lte')

    # completed_tasks

    status_display = django_filters.AllValuesFilter(name='completed_tasks')


    class Meta:
        model = Todo
        fields = ('date', 'end_date', 'status_display' )


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ['project', 'title', 'todo_priority', 'date_todo']
        exclude = ()

TodoFormSet = inlineformset_factory(Project, Todo, form=TodoForm, extra=1)

app/todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views import View

from .forms import LoginForm, TodoFormSet, TodoForm, TodoFilter
from django.shortcuts import redirect, render
from django.contrib.auth import logout
from .models import Post, Project, Todo
from .serializers import TodoSerializer
from django.contrib.auth.forms import UserCreationForm

import django_filters.rest_framework
import django_filters

from rest_framework import routers, serializers, viewsets, filters

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from django.views.generic import FormView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib import messages



class TodoListAPI(generics.ListAPIView):
    queryset = Todo.objects.order_by('date_todo')
    serializer_class = TodoSerializer
    filter_class = TodoFilter
    search_fields = ('title',)
    ordering_fields = ('date_todo', 'title', 'status_display')
    filter_backends = (
        django_filters.rest_framework.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )


class ProjectListView(LoginRequiredMixin, CreateView):
    form_class = TodoForm
    template_name = 'todo/content.html'
    success_url = reverse_lazy('todo:dashboard')

    def get_context_data(self, **kwargs):
        # kwargs['projects'] = Project.objects.exclude(todos__completed_tasks=True)


        kwargs['projects'] = Project.objects.all()
        kwargs['page_title'] = 'Page - Dashboard'
        kwargs['project_todos'] = Todo.objects.exclude(completed_tasks=True)
        # print(request.GET)
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        print("Invalid data")
        return super().form_invalid(form)


class CompletedListView(LoginRequiredMixin, CreateView):
    form_class = TodoForm
    template_name = 'todo/content.html'
    success_url = reverse_lazy('todo:dashboard')

    def get_context_data(self, **kwargs):
        # kwargs['projects'] = Project.objects.exclude(todos__completed_tasks=True)
        kwargs['projects'] = Project.objects.all()
        kwargs['page_title'] = 'Page - Dashboard'
        kwargs['completed'] = True
        kwargs['project_todos'] = Todo.objects.exclude(completed_tasks=False)
        # print(request.GET)
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        print("Invalid data")
        return super().form_invalid(form)


class ProjectCreate(CreateView):
    model = Project
    fields = ['title', 'color']
    success_url = reverse_lazy('todo:dashboard')

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        print("Invalid data")
        messages.error(self.request, 'Invalid data')
        return redirect(reverse('todo:dashboard'))


class ProjecUpdate(UpdateView):
    model = Project
    fields = ['title', 'color']
    success_url = reverse_lazy('todo:dashboard')


class ProjecDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('todo:dashboard')

    def delete(self, request, *args, **kwargs):
        project = Project.objects.get(pk=kwargs['pk'])
        todos = project.todos.all()
        if todos.filter(completed_tasks=False):
            messages.error(request, 'Oops, something bad happened')
            return redirect(reverse('todo:dashboard'))
        else:
            return super().delete(request, *args, **kwargs)


class TodoDelete(DeleteView):
    model = Todo
    success_url = reverse_lazy('todo:dashboard')


class TodoUpdate(UpdateView):
    model = Todo
    fields = ['title', 'completed_tasks', 'todo_priority']
    success_url = reverse_lazy('todo:dashboard')

app/templates/todo/auth.html
{% extends "todo/base.html" %}

{% block title %}Log-in{% endblock %}



{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% else %}
    <p>Please, use the following form to log-in:</p>
  {% endif %}

  <div class="login-form">
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}" />
      <p><input type="submit" value="Log-in"></p>
    </form>

  </div>


{% endblock %}

app/templates/todo/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ page_title }}{% endblock %}</title>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}/">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>


<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href='{% url "landing:home_landing" %}'>Todo bbb</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse" style="">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:dashboard' %}">Link</a>
                </li>
            </ul>
            <ul class="navbar-nav mt-2 mt-md-0">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:todo_completed' %}"><i class="fa fa-list-alt" aria-hidden="true"></i> Completed tasks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url "accounts:logout" %}'>Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href='{% url "accounts:login" %}'>Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url "accounts:registration" %}'>Registration</a>
                </li>
                {% endif %}

            </ul>

        </div>
    </nav>
</header>


<div class="container-fluid">
    <!--Main content code to be written here -->
    <main role="main">

        <div class="marketing">
            {% block content %}
            {% endblock %}

        </div><!-- /.container -->


        <!-- FOOTER -->
        <footer class="container">
            <p class="float-right"><a href="#">Back to top</a></p>
            <p>© 2017-2018 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
        </footer>
    </main>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.min.js"></script>
<script src="https://ace.c9.io/build/src-min-noconflict/ace.js"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
<script src="{% static 'js/colorpicker.js' %}" crossorigin="anonymous"></script>
<script src="https://codepb.github.io/jquery-template/jquery.loadTemplate-0.4.3.js"></script>

<script src="{% static 'js/custom.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/project_todo.js' %}" crossorigin="anonymous"></script>

<script>
    var theInput = document.getElementById("favcolor");
    var theColor = theInput.value;
    theInput.addEventListener("input", function () {

        document.getElementById("favcolor").value = theInput.value;


        console.log(theInput.value)

    }, false);

</script>

</body>
</html>

app/templates/todo/completed_todo_list.html
<div class="cm-all-dynamic-data">
    <div class="cm-dynamic-data">

        {% if messages %}
            <div class="span12">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message|safe }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <!-- Todo Template -->

        {% include "todo/todo_template.html" %}

        <ul id="sortable">
            {% for todo in project_todos %}

                <li class="list-todo">
                    <div class="child-wrap">
                        <div class="input-menu-items">
                            <span class="cm-text-data">{{ todo }} </span>
                            <span class="cm-text-function">{{ todo.project }}</span>
                            <span class="cm-text-function">{{ todo.project.color }}</span>
                        </div>
                        <div class="todo-option">
                            <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                            <div class="block-setting">
                                <form class="delete-form-content" action="{% url 'todo:todo_delete' todo.id %}"
                                      method="post">
                                    <input type="hidden" name="todo_id" value="{{todo.id}}">
                                    <input type="submit" value="Delete"/>
                                </form>
                                <form class="delete-form-content" action="{% url 'todo:todo_update' todo.id %}"
                                      method="post">
                                    <input type="hidden" name="completed_tasks" value="True">
                                    <input type="hidden" class="form-control" name="title" value="{{todo.title}}">
                                    <input type="hidden" class="form-control" name="todo_priority" value="{{todo.todo_priority}}">
                                    <input type="submit" value="Completed"/>
                                </form>

                                <a data-toggle="modal" data-target="#todo_{{todo.id}}">Edit</a>
                            </div>
                        </div>
                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="todo_{{todo.id}}" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">

                                <form class="edit-form-id" action="{% url 'todo:todo_update' todo.id %}" method="post">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="todo_{{todo.id}}_Title">Modal title {{todo.id}}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label>Title</label>
                                            <input type="text" class="form-control" name="title" value="{{todo.title}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Color</label>
                                            <input type="text" class="form-control" name="color" value="">
                                        </div>

                                        <div class="form-group">
                                            {{todo.todo_priority}}
                                            <select name="todo_priority" id="{{todo.id}}">
                                                <option value="high" {% if todo.todo_priority == "high" %} selected {% endif %}>High Priority</option>

                                                <option value="medium" {% if todo.todo_priority == "medium" %} selected {% endif %}>Medium Priority</option>

                                                <option value="low" {% if todo.todo_priority == "low" %} selected {% endif %}>Low Priority</option>

                                            </select>
                                        </div>


                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary">Save changes</button>
                                    </div>

                                </form>


                            </div>
                        </div>
                    </div>

                </li>

            {% endfor %}

            <!--Form add todo-->
            <li class="todo-list">
                <div class="child-wrap">
                    <form class="add-form-content" method="post" action="{% url 'todo:dashboard' %}">
                        {% csrf_token %}

                        <div class="input-menu-items">
                            {{ form.as_table }}

                            <input type="submit" value="Save"/>
                        </div>
                    </form>
                </div>
            </li>

        </ul>

    </div>

    <button class="add-form btn">Add</button>
    <button class="form-close btn">Close</button>
</div>

app/templates/todo/content.html
{% extends "todo/base.html" %}

{% block content %}



    <!-- Three columns of text below the carousel -->
    <div class="row">

        <div class="edit-menu-wrap col-md-12" clear>
            <!--Sidebar-->
            {% include "todo/sidebar.html" %}

            {% if completed %}
                        <!--Todo list-->
                {% include "todo/completed_todo_list.html" %}
            {% else %}
                        <!--Todo list-->
                {% include "todo/todo_list.html" %}
            {% endif %}


        </div>


        <div class="editor-wrapper">
            <div id="editor"></div>
        </div>

        <div class="modals-overlay"></div>
        <div class="cm-model-wrapper">
            <div class="cm-project-modal" modal-data="add-website">

                <form enctype="multipart/form-data" class="add-project" id="form_project" method="post" action="{% url 'todo:project_create' %}">
                    {% csrf_token %}
                    <div class="cm-project-modal-header">
                        <label>Create New Project</label>
                    </div>
                    <div class="cm-project-setting-inner-wrapper">
                      <div class="color-field">
                           <input type="color" id="favcolor" name="color" value="" />
                           <input class="field-show project-title" type="text" name="title"/>


                          <div class="color-block">
                              <a class="paper-button ripple">&nbsp;</a>
                            <div class="translate">
                              <div class="color-picker" data-value="#2196F3">
                                <div class="red"></div>
                                <div class="blue"></div>
                                <div class="green"></div>
                                <div class="indigo"></div>
                                <div class="brown"></div>
                                <div class="black"></div>
                                <div class="teal"></div>
                                <div class="deep-orange"></div>
                                <div class="light-blue"></div>
                                <div class="light-green"></div>
                                <div class="deep-purple"></div>
                                <div class="amber"></div>
                                <div class="blue-gray"></div>
                                <div class="pink"></div>
                                <div class="orange"></div>
                                <div class="cyan"></div>
                                <div class="lime"></div>
                                <div class="purple"></div>
                                <div class="yellow"></div>
                                <div class="gray"></div>
                                <div class="white"></div>
                                <div class="transparent"></div>
                                <input type="color" id="colorinput">
                                <span class="hex">
                                  <input type="text" id="text">
                                  <div class="underline"></div>
                                </span>
                                <div id="close">
                                  <i class="material-icons">close</i>
                                </div>
                              </div>
                            </div>
                          </div>

                      </div>

                    </div>
                    <div class="cm-project-modal-footer">
                        <div class="form-action-box">
                            <button class="data-file-save btn-def button-add" model-close>Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

{% endblock %}

app/templates/todo/error_404.html
{% extends "todo/base.html" %}

{% block content %}


<h1> 404  </h1>

{% endblock %}

app/templates/todo/get_api.html
My api TEST

{% for item in projects %}

    {{item}}

{% endfor %}

app/templates/todo/sidebar.html
<div class="cm-all-menu-items">
    <div class="cm-project-list">
        <ul>
            <li>
                <a href="{% url 'todo:todo_api' %}" class="get-today-todo" data-date="">
                    Today
                </a>
            </li>
            <li>
                <a href="#" class="get-today-seven" data-date="">
                    Next 7 day
                </a>
            </li>
            {% for item in projects %}

            <li data-id="{{item.id}}">
                <div class="cm-proj-mane">
                    <a>
                        <i class="fa fa-cube" aria-hidden="true"></i>{{item.title}}
                        <span class="color-project">{{item.color}}</span>
                    </a>
                </div>
                <div class="cm-proj-option">
                    <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                    <div class="project-option">
                        <span class="color-project">
                            <a data-toggle="modal" data-target="#projectedit_{{item.id}}">Edit</a>
                        </span>

                        <span class="color-project">

                            <form action="{% url 'todo:project_delete' item.id %}" method="post">
                                <input type="hidden" name="project_id" value="{{item.id}}">
                                <button type="submit">Delete</button>

                            </form>
                        </span>
                    </div>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="projectedit_{{item.id}}" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">

                            <form action="{% url 'todo:project_update' item.id %}" method="post">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="projectedit_{{item.id}}_Title">Modal title
                                        {{item.id}}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label>Title</label>
                                        <input type="text" class="form-control" name="title" value="{{item.title}}">
                                    </div>
                                    <div class="form-group">
                                        <label>Color</label>
                                        <input type="text" class="form-control" name="color" value="{{item.color}}">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>


            </li>
            {% endfor %}

        </ul>
    </div>
    <div class="cm-file-menu-option">
        <ul>
            <li modal-click="add-website" class="cm-add-website" title="Add Project">
                <i class="fa fa-plus" aria-hidden="true"></i>
            </li>
        </ul>
    </div>
</div>

app/templates/todo/test.html
{% extends "todo/todo.html" %}

{% block content %}

  <h1>My Blog 3</h1>


{% endblock %}