app/accounts/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views

from accounts import views



urlpatterns = [
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('register/quest/', views.GuestFormView.as_view(), name='quest_register'),
    path('registration/', views.RegisterFormView.as_view(), name='registration'),
    path('logout/', views.logout_view, name='logout'),

    path('account/', views.AccountHomeView.as_view(), name='account'),

    path('email/confirm/<key>/', views.AccountEmailActivateView.as_view(), name='email-activate'),



]

app_name = 'accounts'



urlpatterns = format_suffix_patterns(urlpatterns)

app/landing/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from landing import views


urlpatterns = [
    path('', views.HomeLandingView.as_view(), name='home_landing'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),


]

app_name = 'landing'



urlpatterns = format_suffix_patterns(urlpatterns)

app/marketing/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns


from . import views

urlpatterns = [
    path('settings/email/', views.MarketingPreferenceUpdateView.as_view(), name='marketing_pref'),

]

app_name = 'marketing'



urlpatterns = format_suffix_patterns(urlpatterns)

app/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace="todo")),
    path('', include('orders.urls', namespace="orders")),
    path('', include('products.urls', namespace="products")),
    path('', include('landing.urls', namespace="landing")),
    path('', include('parsersapi.urls', namespace="parsersapi")),
    path('', include('search.urls', namespace="search")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('billing.urls', namespace="billing")),
    path('', include('marketing.urls', namespace="marketing")),
    path('', include('analytics.urls', namespace="analytics")),

    # path('auth/social', auth_social.home, name="auth-social"),

    path('auth/social/', include('social_django.urls', namespace="social")),

    # path('', include('django.contrib.auth.urls', namespace='auth')),

    # url('', include('django.contrib.auth.urls', namespace='auth')),
    # url('', include('social.apps.django_app.urls', namespace='social')),

    path('accounts/password/change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password/change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # path('', views.index, name='home'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/parsersapi/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from . import views



urlpatterns = [
    path('parser-api/', views.ParserApiView.as_view(), name='parserapi'),
    path('parser_get/', views.parser_get, name='parser_get'),
    path('parser/API/', views.ParserApiRest.as_view(), name='parser_api'),
    path('csv_parse/', views.csv_parse, name='csv_parse'),
    path('blog/', views.PostsListView.as_view(), name='posts'),
    path('blog/<slug:slug>/', views.PostsDetailView.as_view(), name='post_detail'),

]

app_name = 'parsersapi'



urlpatterns = format_suffix_patterns(urlpatterns)

app/products/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from products import views


urlpatterns = [
    path('product/<slug:slug>/', views.ProductsDetailView.as_view(), name='product_detail'),
    path('products/API/', views.ProductRestApi.as_view(), name='product_api'),
    path('shop/', views.ShopProductListView.as_view(), name='shop'),

    path('product/<slug>/<pk>/', views.ProductDownloadView.as_view(), name='download'),

]

app_name = 'products'

urlpatterns = format_suffix_patterns(urlpatterns)

app/todo/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from todo import views



urlpatterns = [
    path('dashboard/', views.ProjectListView.as_view(), name='dashboard'),
    path('project-create/', views.ProjectCreate.as_view(), name='project_create'),
    # projec/2/delete/
    path('project/<int:pk>/delete/', views.ProjecDelete.as_view(), name='project_delete'),
    path('todo/<int:pk>/delete/', views.TodoDelete.as_view(), name='todo_delete'),
    # projec/2/update/
    path('project/<int:pk>/update/', views.ProjecUpdate.as_view(), name='project_update'),
    path('todo/<int:pk>/update/', views.TodoUpdate.as_view(), name='todo_update'),
    path('todo/API/', views.TodoListAPI.as_view(), name='todo_api'),
    path('todo/completed/', views.CompletedListView.as_view(), name='todo_completed'),


]

app_name = 'todo'



urlpatterns = format_suffix_patterns(urlpatterns)

app/landing/forms.py
from django import forms


class ContactPageForm(forms.Form):
    fullname = forms.CharField(
            widget=forms.TextInput(
                    attrs={
                        "class": "form-control",
                        "placeholder": "Your full name"
                    }
                )
            )
    email    = forms.EmailField(
            widget=forms.EmailInput(
                    attrs={
                        "class": "form-control",
                        "placeholder": "Your email"
                    }
                )
            )
    content  = forms.CharField(
            widget=forms.Textarea(
                attrs={
                    'class': 'form-control',
                    "placeholder": "Your message"
                    }
                )
            )
    # def clean_email(self):
    #     email = self.cleaned_data.get("email")
    #     if not "gmail.com" in email:
    #         raise forms.ValidationError("Email has to be gmail.com")
    #     return email
    #
    # def clean_content(self):
    #     raise forms.ValidationError("Content is wrong")

app/landing/views.py
from django.views.generic import FormView, ListView, TemplateView
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse, HttpResponse
from .forms import ContactPageForm
from products.models import Product, ProductCategory
from shops.models import Shop, LocationShop
from todo.models import Post

from django.core.mail import EmailMultiAlternatives



class HomeLandingView(TemplateView):

    template_name = 'landing/home_content.html'

    def get_context_data(self, **kwargs):
        kwargs['page_title'] = 'Page - Landing'
        kwargs['products'] = Product.objects.all()
        kwargs['products_category'] = ProductCategory.objects.filter(is_active=True)
        kwargs['posts'] = Post.objects.all()[:3]

        return super().get_context_data(**kwargs)


class ContactPageView(FormView):
    form_class = ContactPageForm

    template_name = 'landing/contact-page.html'
    success_url = reverse_lazy('landing:contact')

    def get_context_data(self, **kwargs):
        kwargs['shops'] = LocationShop.objects.filter(shop__is_active=True)

        return super().get_context_data(**kwargs)


    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).



        response = super().form_valid(form)
        if self.request.is_ajax():

            email = form.cleaned_data.get('email')
            fullname = form.cleaned_data.get('fullname')
            content = form.cleaned_data.get('content')

            subject, from_email, to = 'hello', email, 'pivnychenko.light.it@gmail.com'
            text_content = 'This breeee is an important message. '
            html_content = '<p>This is an <strong>important</strong> message. {} Name: {}</p>'.format(content, fullname)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            data = {
                'data': form.cleaned_data,
                'url': self.success_url,
                'message': "Thank you for your submission!"
            }
            return JsonResponse(data, status=200)
        else:
            return response

    def form_invalid(self, form):
        response = super().form_valid(form)
        errors = form.errors.as_json()
        if self.request.is_ajax():
            return HttpResponse(errors, status=400, content_type='application/json')
        else:
            return response

app/templates/landing/contact-page.html
{% extends "base.html" %}
{% load static %}
{% block content %}



	<!-- Product -->




	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="{% url 'landing:home_landing' %}" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>
			<span class="stext-109 cl4">
				{{ page_title }}


			</span>
		</div>
	</div>


	<!-- Title page -->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style='background-image: url({% static "images/bg-01.jpg" %});'>
		<h2 class="ltext-105 cl0 txt-center title-upper">
			{{ page_title }}
		</h2>
	</section>


	<!-- Content page -->
	<section class="bg0 p-t-104 p-b-116">
		<div class="container">
			<div class="flex-w flex-tr">
				<div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">

					<form method="post" action="{% url 'landing:contact' %}" id="form-contact">

						<div class="m-b-30">
                            <h4 class="mtext-105 cl2 txt-center p-b-30">
                                Send Us A Message
                            </h4>
                            {% csrf_token %}
                            {{ form.as_p }}

						</div>

						<button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
							Submit
						</button>
					</form>
				</div>

				<div class="size-210 bor10 flex-w flex-col-m p-lr-93 p-tb-30 p-lr-15-lg w-full-md">
					<div class="flex-w w-full p-b-42">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-map-marker"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Address
							</span>

							<p class="stext-115 cl6 size-213 p-t-18">
								Center 8th floor, 379 Hudson St, New York, NY 10018 US
							</p>
						</div>
					</div>

					<div class="flex-w w-full p-b-42">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-phone-handset"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Lets Talk
							</span>

							<p class="stext-115 cl1 size-213 p-t-18">
								+1 800 1236879
							</p>
						</div>
					</div>

					<div class="flex-w w-full">
						<span class="fs-18 cl5 txt-center size-211">
							<span class="lnr lnr-envelope"></span>
						</span>

						<div class="size-212 p-t-2">
							<span class="mtext-110 cl2">
								Sale Support
							</span>

							<p class="stext-115 cl1 size-213 p-t-18">
								contact@example.com
							</p>
						</div>
					</div>
				</div>
			</div>

		</div> <!-- .container -->

	</section>

  <script src="http://maps.google.com/maps/api/js?sensor=false"
          type="text/javascript"></script>

  <div id="map" style="height: 400px;"></div>

  <script type="text/javascript">
  var country = "United States"
	var locations = [
		{% for items in shops %}
			["{{ items.title }}", {{ items.latitude }}, {{ items.longitude }}]{% if not forloop.last %}, {% endif %}
		{% endfor %}
	];

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 3,
      center: new google.maps.LatLng(39.5, -98.35) || map.setCenter(marker.getPosition()),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  </script>


	<!-- Map -->
	<div class="map">
		<div class="size-303" id="google_map" data-map-x="40.691446" data-map-y="-73.886787" data-pin="images/icons/pin.png" data-scrollwhell="0" data-draggable="1" data-zoom="11"></div>
	</div>


{% endblock %}

app/templates/landing/header.html
<!-- Header -->
<header>
    <!-- Header desktop -->
    <div class="container-menu-desktop">
        <!-- Topbar -->
        <div class="top-bar">
            <div class="content-topbar flex-sb-m h-full container">
                <div class="left-top-bar">
                    Free shipping for standard order over $100
                </div>

                <div class="right-top-bar flex-w h-full">
                    <a href="#" class="flex-c-m trans-04 p-lr-25">
                        Help & FAQs
                    </a>

                    <a href="#" class="flex-c-m trans-04 p-lr-25">
                        EN
                    </a>

                    <a href="#" class="flex-c-m trans-04 p-lr-25">
                        USD
                    </a>
                </div>
            </div>
        </div>

        <div class="wrap-menu-desktop">
            <nav class="limiter-menu-desktop container">

                <!-- Logo desktop -->
                <a href="#" class="logo">
                    <img src="static/images/icons/logo-01.png" alt="IMG-LOGO">
                </a>

                <!-- Menu desktop -->
                <div class="menu-desktop">
                    <ul class="main-menu">
                        <li class="active-menu">
                            <a href="/">Home</a>
                        </li>

                        <li>
                            <a href="{% url 'products:shop' %}">Shop</a>
                        </li>


                        <li>
                            <a href="{% url 'landing:contact' %}">Contact</a>
                        </li>

                        <li>
                            <a href="{% url 'parsersapi:posts' %}">Blog</a>
                        </li>
                    </ul>
                </div>

                <!-- Icon header -->
                <div class="wrap-icon-header flex-w flex-r-m">
                    <div class="dropdown">
						  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							My Account
						  </button>
						  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

							  {% if request.user.is_authenticated %}
							  	<a href="{% url 'accounts:account' %}" class="dropdown-item">
									Home
								</a>
								<a href="{% url 'marketing:marketing_pref' %}" class="dropdown-item">
									Settings
								</a>
							  	<a href="{% url 'accounts:logout' %}" class="dropdown-item">
									Logout
								</a>
							  {% else %}

								<a href="{% url 'accounts:login' %}" class="dropdown-item">
									Login
								</a>
								<a href="{% url 'accounts:registration' %}" class="dropdown-item">
									Registration
								</a>

							  {% endif %}
						  </div>
                    </div>
                    <div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
                        <i class="zmdi zmdi-search"></i>
                    </div>

                    <div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart" data-notify="{% if products_total_nmb %}{{ products_total_nmb }}{% else %}0{% endif %}">
                        <i class="zmdi zmdi-shopping-cart"></i>
                    </div>

                </div>
            </nav>
        </div>
    </div>

    <!-- Header Mobile -->
    <div class="wrap-header-mobile">
        <!-- Logo moblie -->
        <div class="logo-mobile">
            <a href="index.html"><img src="static/images/icons/logo-01.png" alt="IMG-LOGO"></a>
        </div>

        <!-- Icon header -->
        <div class="wrap-icon-header flex-w flex-r-m m-r-15">
            <div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search">
                <i class="zmdi zmdi-search"></i>
            </div>

            <div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart" data-notify="{{ products_total_nmb }}">
                <i class="zmdi zmdi-shopping-cart"></i>
            </div>
        </div>

        <!-- Button show menu -->
        <div class="btn-show-menu-mobile hamburger hamburger--squeeze">
            <span class="hamburger-box">
                <span class="hamburger-inner"></span>
            </span>
        </div>
    </div>


    <!-- Menu Mobile -->
    <div class="menu-mobile">
        <ul class="topbar-mobile">
            <li>
                <div class="left-top-bar">
                    Free shipping for standard order over $100
                </div>
            </li>

            <li>
                <div class="right-top-bar flex-w h-full">
                    <a href="#" class="flex-c-m p-lr-10 trans-04">
                        Help & FAQs
                    </a>

                    <a href="{% url 'accounts:login' %}" class="flex-c-m p-lr-10 trans-04">
                        My Account
                    </a>

                    <a href="#" class="flex-c-m p-lr-10 trans-04">
                        EN
                    </a>

                    <a href="#" class="flex-c-m p-lr-10 trans-04">
                        USD
                    </a>
                </div>
            </li>
        </ul>

        <ul class="main-menu-m">
            <li>
                <a href="index.html">Home</a>
                <ul class="sub-menu-m">
                    <li><a href="index.html">Homepage 1</a></li>
                    <li><a href="home-02.html">Homepage 2</a></li>
                    <li><a href="home-03.html">Homepage 3</a></li>
                </ul>
                <span class="arrow-main-menu-m">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </span>
            </li>

            <li>
                <a href="product.html">Shop</a>
            </li>

            <li>
                <a href="shoping-cart.html" class="label1 rs1" data-label1="hot">Features</a>
            </li>

            <li>
                <a href="blog.html">Blog</a>
            </li>


            <li>
                <a href="{% url 'landing:contact' %}">Contact</a>
            </li>
        </ul>
    </div>

    <!-- Modal Search -->
    <div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
        <div class="container-search-header">
            <button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
                <img src="static/images/icons/icon-close2.png" alt="CLOSE">
            </button>

            {% include "search/form.html" %}
        </div>
    </div>
</header>