app/accounts/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views

from accounts import views



urlpatterns = [
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('register/quest/', views.GuestFormView.as_view(), name='quest_register'),
    path('registration/', views.RegisterFormView.as_view(), name='registration'),
    path('logout/', views.logout_view, name='logout'),

    path('account/', views.AccountHomeView.as_view(), name='account'),

    path('email/confirm/<key>/', views.AccountEmailActivateView.as_view(), name='email-activate'),



]

app_name = 'accounts'



urlpatterns = format_suffix_patterns(urlpatterns)

app/analytics/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns


from . import views


urlpatterns = [

    path('analytics/sales/', views.SalesView.as_view(), name='sales'),

    path('analytics/sales/data/', views.SalesAjaxView.as_view(), name='sales-data'),

]

app_name = 'analytics'

urlpatterns = format_suffix_patterns(urlpatterns)

app/landing/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from landing import views


urlpatterns = [
    path('', views.HomeLandingView.as_view(), name='home_landing'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),


]

app_name = 'landing'



urlpatterns = format_suffix_patterns(urlpatterns)

app/marketing/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns


from . import views

urlpatterns = [
    path('settings/email/', views.MarketingPreferenceUpdateView.as_view(), name='marketing_pref'),

]

app_name = 'marketing'



urlpatterns = format_suffix_patterns(urlpatterns)

app/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace="todo")),
    path('', include('orders.urls', namespace="orders")),
    path('', include('products.urls', namespace="products")),
    path('', include('landing.urls', namespace="landing")),
    path('', include('parsersapi.urls', namespace="parsersapi")),
    path('', include('search.urls', namespace="search")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('billing.urls', namespace="billing")),
    path('', include('marketing.urls', namespace="marketing")),
    path('', include('analytics.urls', namespace="analytics")),

    # path('auth/social', auth_social.home, name="auth-social"),

    path('auth/social/', include('social_django.urls', namespace="social")),

    # path('', include('django.contrib.auth.urls', namespace='auth')),

    # url('', include('django.contrib.auth.urls', namespace='auth')),
    # url('', include('social.apps.django_app.urls', namespace='social')),

    path('accounts/password/change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password/change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # path('', views.index, name='home'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/orders/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns


from . import views

urlpatterns = [
    path('basket_adding/', views.basket_adding, name='basket_adding'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout-address-shipping', views.CheckoutAddressView.as_view(), name='address_shipping'),
    path('order/success/', views.checkout_done_view, name='success'),
    path('orders/', views.OrderListView.as_view(), name='list'),
    path('orders/<order_id>/', views.OrderDetailView.as_view(), name='detail'),

]

app_name = 'orders'



urlpatterns = format_suffix_patterns(urlpatterns)

app/todo/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from todo import views



urlpatterns = [
    path('dashboard/', views.ProjectListView.as_view(), name='dashboard'),
    path('project-create/', views.ProjectCreate.as_view(), name='project_create'),
    # projec/2/delete/
    path('project/<int:pk>/delete/', views.ProjecDelete.as_view(), name='project_delete'),
    path('todo/<int:pk>/delete/', views.TodoDelete.as_view(), name='todo_delete'),
    # projec/2/update/
    path('project/<int:pk>/update/', views.ProjecUpdate.as_view(), name='project_update'),
    path('todo/<int:pk>/update/', views.TodoUpdate.as_view(), name='todo_update'),
    path('todo/API/', views.TodoListAPI.as_view(), name='todo_api'),
    path('todo/completed/', views.CompletedListView.as_view(), name='todo_completed'),


]

app_name = 'todo'



urlpatterns = format_suffix_patterns(urlpatterns)

app/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.urls import reverse_lazy, reverse
from django.utils.safestring import mark_safe
from django.contrib import messages

User = get_user_model()

from .models import EmailActivation

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'full_name',) #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password', 'is_active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class GuestForm(forms.Form):
	email = forms.EmailField()


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def clean(self):
        request = self.request
        data = self.cleaned_data
        email  = data.get("email")
        password  = data.get("password")

        print(request)

        qs = User.objects.filter(email=email)
        if qs.exists():
            # user email is registered, check active/
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                ## not active, check email activation
                link = reverse("accounts:login")
                reconfirm_msg = """Go to <a href='{resend_link}'>
                resend confirmation email</a>.
                """.format(resend_link = link)
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account "
                    messages.error(request, mark_safe(msg1))
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))
                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError("This user is inactive.")
        user = authenticate(request, username=email, password=password)
        if not user:
            messages.error(self.request, 'You are not registred')
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        self.user = user
        return data


class SignUpForm(forms.ModelForm):
	"""A form for creating new users. Includes all the required
	fields, plus a repeated password."""
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('full_name', 'email',)  # 'full_name',)

	def clean_password2(self):
		# Check that the two password entries match
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
		return password2

	def save(self, commit=True):
		# Save the provided password in hashed format
		user = super().save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		user.is_active = False  # send confirmation email via signals
		# obj = EmailActivation.objects.create(user=user)
		# obj.send_activation_email()
		if commit:
			user.save()
		return user

app/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from .forms import LoginForm, GuestForm, SignUpForm
from django.shortcuts import redirect, render
from django.views.generic import FormView, CreateView, DetailView, View
from django.views.generic.edit import FormMixin
from django.contrib.auth import logout
from .models import GuestEmail, EmailActivation
from .signals import user_logged_in
from django.utils.safestring import mark_safe
from myproject.mixins import RequestFormAttachMixin

class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'

    def get_object(self):
        return self.request.user


class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'

    def get(self, request, key, *args, **kwargs):
        qs = EmailActivation.objects.filter(key__iexact=key)
        confirm_qs = qs.confirmable()
        if confirm_qs.count() == 1:
            obj = qs.first()
            obj.activate()
            messages.success(request, "Your email has been confirmed. Please login.")
            return redirect("accounts:login")
        else:
            activated_qs = qs.filter(activated=True)
            if activated_qs.exists():
                reset_link = reverse("password_reset")
                msg = """Your email has already been confirmed
                Do you need to <a href="{link}">reset your password</a>?
                """.format(link=reset_link)
                messages.success(request, mark_safe(msg))
                return redirect("accounts:login")

        context = {'key': key}

        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class GuestFormView(FormView):
    template_name = 'accounts/auth.html'
    form_class = GuestForm

    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        session_key = self.request.session.session_key
        email = cleaned_data.get("email")

        new_guest_email = GuestEmail.objects.filter(email=email).first()
        if not new_guest_email:
            new_guest_email = GuestEmail.objects.create(email=email, session_key=session_key)

        self.request.session['guest_email_id'] = new_guest_email.id
        return redirect(reverse('orders:checkout'))

    def form_invalid(self, form):
        return redirect(reverse('orders:checkout'))


class LoginFormView(RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/auth.html'

    def form_valid(self, form):
        return super().form_valid(form)


class RegisterFormView(CreateView):
    template_name = 'accounts/registration.html'
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return redirect(reverse('accounts:registration'))


def logout_view(request):
    logout(request)
    return redirect(reverse('accounts:login'))
    # Redirect to a success page.

app/templates/accounts/auth.html
{% extends "base.html" %}

{% block content %}

	<!-- login-form -->

<div class="container">
    <div class="row">

        <div class="login-form col-lg-8 col-md-10 mx-auto bg0 p-t-104 p-b-116">
            <form action="." method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />

                <p>
                    <button type="submit" class="btn btn-primary" >Log-in</button>

                    <a href="{% url 'password_reset' %}">Reset your Password</a>


                    <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>

                    <a href="{% url 'social:begin' 'github' %}">Login with Github</a>

                    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>

                </p>
            </form>

        </div>

    </div>
</div>



{% endblock %}

app/templates/accounts/guest_form.html
<form class="login-form" action="{{ action_url }}" method="post">
    {% if address_type %}
        <input type='hidden' name='address_type' value='{{ address_type }}' />
    {% endif %}
    {{ form }}
    {% csrf_token %}
    <input type="submit" class="button" value="Submit">
</form><!--.quest-form-->

app/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}

	<!-- login-form -->

<div class="container">
    <div class="row">





        <div class='col-12'>
            <h1>Account</h1>
            <hr/>
        </div>
    <div class='col-12 col-md-3 my-3'>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Support</h4>
                <div class='list-group'>
                    <a class='list-group-item' href=''>About</a>
                    <a class='list-group-item' href="{% url 'landing:contact' %}">Contact</a>
                </div>
          </div>
        </div>
    </div>



    <div class='col-12 col-md-3 my-3' id='billing'>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Billing</h4>
                <div class='list-group'>
                    <a class='list-group-item' href='{% url "orders:list" %}'>Orders</a>
                    <a class='list-group-item' href='{% url "analytics:sales" %}'>Analytics Sales</a>
                    <!--<a class='list-group-item' href=''>Addresses</a>-->


                </div>
          </div>
        </div>
    </div>


    <div class='col-12 col-md-3 my-3'>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Account Details</h4>
                <div class='list-group'>
                    <a class='list-group-item' href='{% url "password_change" %}'>Change Password</a>

                </div>

          </div>
        </div>
    </div>


    <div class='col-12 col-md-3 my-3'>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Preferences</h4>
                <div class='list-group'>
                    <a class='list-group-item' href="{% url 'marketing:marketing_pref' %}">Email Marketing</a>

                </div>

          </div>
        </div>
    </div>


    <div class='col-12 col-md-3 my-3'>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">History</h4>
                  <div class='list-group'>
                    <a class='list-group-item' href=''>Products</a>
                </div>
          </div>
        </div>
    </div>







    </div>
</div>



{% endblock %}

app/templates/accounts/registration.html
{% extends "base.html" %}

{% block content %}

	<!-- login-form -->

<div class="container">
    <div class="row">

        <div class="login-form col-lg-8 col-md-10 mx-auto bg0 p-t-104 p-b-116">
            <form action="." method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <p>
                    <button type="submit" class="btn btn-primary" >Registration</button>
                </p>
            </form>
        </div>

    </div>
</div>



{% endblock %}