app/accounts/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views

from accounts import views



urlpatterns = [
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('register/quest/', views.GuestFormView.as_view(), name='quest_register'),
    path('registration/', views.RegisterFormView.as_view(), name='registration'),
    path('logout/', views.logout_view, name='logout'),

    path('account/', views.AccountHomeView.as_view(), name='account'),

    path('email/confirm/<key>/', views.AccountEmailActivateView.as_view(), name='email-activate'),



]

app_name = 'accounts'



urlpatterns = format_suffix_patterns(urlpatterns)

app/landing/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from landing import views


urlpatterns = [
    path('', views.HomeLandingView.as_view(), name='home_landing'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),


]

app_name = 'landing'



urlpatterns = format_suffix_patterns(urlpatterns)

app/marketing/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns


from . import views

urlpatterns = [
    path('settings/email/', views.MarketingPreferenceUpdateView.as_view(), name='marketing_pref'),

]

app_name = 'marketing'



urlpatterns = format_suffix_patterns(urlpatterns)

app/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace="todo")),
    path('', include('orders.urls', namespace="orders")),
    path('', include('products.urls', namespace="products")),
    path('', include('landing.urls', namespace="landing")),
    path('', include('parsersapi.urls', namespace="parsersapi")),
    path('', include('search.urls', namespace="search")),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('billing.urls', namespace="billing")),
    path('', include('marketing.urls', namespace="marketing")),
    path('', include('analytics.urls', namespace="analytics")),

    # path('auth/social', auth_social.home, name="auth-social"),

    path('auth/social/', include('social_django.urls', namespace="social")),

    # path('', include('django.contrib.auth.urls', namespace='auth')),

    # url('', include('django.contrib.auth.urls', namespace='auth')),
    # url('', include('social.apps.django_app.urls', namespace='social')),

    path('accounts/password/change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password/change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # path('', views.index, name='home'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/products/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from products import views


urlpatterns = [
    path('product/<slug:slug>/', views.ProductsDetailView.as_view(), name='product_detail'),
    path('products/API/', views.ProductRestApi.as_view(), name='product_api'),
    path('shop/', views.ShopProductListView.as_view(), name='shop'),

    path('product/<slug>/<pk>/', views.ProductDownloadView.as_view(), name='download'),

]

app_name = 'products'

urlpatterns = format_suffix_patterns(urlpatterns)

app/todo/urls.py
from django.urls import path, include
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import handler404, handler500

from todo import views



urlpatterns = [
    path('dashboard/', views.ProjectListView.as_view(), name='dashboard'),
    path('project-create/', views.ProjectCreate.as_view(), name='project_create'),
    # projec/2/delete/
    path('project/<int:pk>/delete/', views.ProjecDelete.as_view(), name='project_delete'),
    path('todo/<int:pk>/delete/', views.TodoDelete.as_view(), name='todo_delete'),
    # projec/2/update/
    path('project/<int:pk>/update/', views.ProjecUpdate.as_view(), name='project_update'),
    path('todo/<int:pk>/update/', views.TodoUpdate.as_view(), name='todo_update'),
    path('todo/API/', views.TodoListAPI.as_view(), name='todo_api'),
    path('todo/completed/', views.CompletedListView.as_view(), name='todo_completed'),


]

app_name = 'todo'



urlpatterns = format_suffix_patterns(urlpatterns)

app/templates/content_parser.html
{% extends "base.html" %}

{% block content %}



	<!-- Product -->

	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="{% url 'landing:home_landing' %}" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				Checkout
			</span>
		</div>
	</div>



	<div class="container">
		<table id="example" class="display" style="width:100%">
			<thead>
				<tr>
					<th></th>
					<th>Name</th>
					<th>Email</th>
					<th>Adress</th>
					<th>Page</th>
					<th>Publish</th>
				</tr>
			</thead>
			<tbody>


				{%for item in parseapi%}
					<tr>
						<td></td>
						<td>{{item}}</td>
						<td>{{item.email}}</td>
						<td>{{item.address}}</td>
						<td>{{item.web_page}}</td>
						<td>{{item.publish}}</td>
					</tr>
				{%endfor%}
			</tbody>
			<tfoot>
				<tr>
					<th></th>
					<th>Name</th>
					<th>Email</th>
					<th>Adress</th>
					<th>Page</th>
					<th>Publish</th>
				</tr>
			</tfoot>
		</table>

		<a href="{% url 'parsersapi:csv_parse' %}" class="flex-c-m stext-101 cl0 col-sm-3 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
			csv parse
		</a>

	</div>





	<!-- Shoping Cart -->
	<form class="bg0 p-t-75 p-b-85" action="{% url 'parsersapi:parser_get' %}" id="form-parser-api">
		{% csrf_token %}
		<div class="container">
			<div class="row">


				<div class="col-sm-12 m-lr-auto m-b-50">
					<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
						<h4 class="mtext-109 cl2 p-b-30">
							Parser API
						</h4>



						<div class="flex-w flex-t bor12 p-t-15 p-b-30">
							<div class="size-209 p-r-18 p-r-0-sm w-full-ssm">
								<p class="stext-111 cl6 p-t-2">
									There are no shipping methods available. Please double check your address, or contact us if you need any help.
									https://www.usacycling.org/API/events/?&page_start=10
								</p>

								<div class="p-t-15">
									<span class="stext-112 cl8">
										Calculate Shipping
									</span>



									<div class="bor8 bg0 m-b-12">
										<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="url" placeholder="url">

									</div>

									<div class="bor8 bg0 m-b-22">
										<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="numb_count" id="numb_count" placeholder="Count">
									</div>

									<div class="bor8 bg0 m-b-22">
										<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="news_api" id="news-api" placeholder="News">
									</div>


								</div>
							</div>
						</div>


						<button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
							Proceed to Checkout
						</button>
					</div>
				</div>
			</div>
		</div>
	</form>


{% endblock %}

app/templates/header.html
{% load static %}
<!-- Header -->



	<!-- Header -->
	<header class="header-v4">
		<!-- Header desktop -->
		<div class="container-menu-desktop">
			<!-- Topbar -->
			<div class="top-bar">
				<div class="content-topbar flex-sb-m h-full container">
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>

					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m trans-04 p-lr-25">
							Help & FAQs
						</a>
						<a href="#" class="flex-c-m trans-04 p-lr-25">
							EN
						</a>

						<a href="#" class="flex-c-m trans-04 p-lr-25">
							USD
						</a>
					</div>
				</div>
			</div>

			<div class="wrap-menu-desktop how-shadow1">
				<nav class="limiter-menu-desktop container">

					<!-- Logo desktop -->
					<a href="{% url 'landing:home_landing' %}" class="logo">
						<img src='{% static "images/icons/logo-01.png" %}' alt="IMG-LOGO">
					</a>

					<!-- Menu desktop -->
					<div class="menu-desktop">
						<ul class="main-menu">
							<li>
								<a href="/">Home</a>
							</li>

							<li>
								<a href="{% url 'products:shop' %}">Shop</a>
							</li>


							<li>
								<a href="{% url 'landing:contact' %}">Contact</a>
							</li>
							<li>
                            	<a href="{% url 'parsersapi:posts' %}">Blog</a>
                        	</li>
						</ul>
					</div>

					<!-- Icon header -->
					<div class="wrap-icon-header flex-w flex-r-m">
						<div class="dropdown">
						  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							My Account
						  </button>
						  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

							  {% if request.user.is_authenticated %}
							  	<a href="{% url 'accounts:account' %}" class="dropdown-item">
									Home
								</a>
								<a href="{% url 'marketing:marketing_pref' %}" class="dropdown-item">
									Settings
								</a>
							  	<a href="{% url 'accounts:logout' %}" class="dropdown-item">
									Logout
								</a>
							  	<a href="{% url 'todo:dashboard' %}" class="dropdown-item">
									Todo
								</a>

							  {% else %}

								<a href="{% url 'accounts:login' %}" class="dropdown-item">
									Login
								</a>
								<a href="{% url 'accounts:registration' %}" class="dropdown-item">
									Registration
								</a>

							  {% endif %}
						  </div>
						</div>
						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
							<i class="zmdi zmdi-search"></i>
						</div>

						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart" data-notify="{{ products_total_nmb }}">
							<i class="zmdi zmdi-shopping-cart"></i>
						</div>

					</div>
				</nav>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap-header-mobile">
			<!-- Logo moblie -->
			<div class="logo-mobile">
				<a href="index.html"><img src='{% static "images/icons/logo-01.png" %}' alt="IMG-LOGO"></a>
			</div>

			<!-- Icon header -->
			<div class="wrap-icon-header flex-w flex-r-m m-r-15">
				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search">
					<i class="zmdi zmdi-search"></i>
				</div>

				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart" data-notify="{{ products_total_nmb }}">
					<i class="zmdi zmdi-shopping-cart"></i>
				</div>
			</div>

			<!-- Button show menu -->
			<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
				<span class="hamburger-box">
					<span class="hamburger-inner"></span>
				</span>
			</div>
		</div>


		<!-- Menu Mobile -->
		<div class="menu-mobile">
			<ul class="topbar-mobile">
				<li>
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>
				</li>

				<li>
					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m p-lr-10 trans-04">
							Help & FAQs
						</a>

						<a href="{% url 'accounts:login' %}" class="flex-c-m p-lr-10 trans-04">
							My Account
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							EN
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							USD
						</a>
					</div>
				</li>
			</ul>

			<ul class="main-menu-m">
				<li>
					<a href="/">My Account</a>
					<ul class="sub-menu-m" >
						<li><a href="index.html">Homepage 1</a></li>
						<li><a href="home-02.html">Homepage 2</a></li>
						<li><a href="home-03.html">Homepage 3</a></li>
					</ul>
					<span class="arrow-main-menu-m">
						<i class="fa fa-angle-right" aria-hidden="true"></i>
					</span>
				</li>

				<li>
					<a href="product.html">Shop</a>
				</li>


				<li>
					<a href="about.html">About</a>
				</li>

				<li>
					<a href="{% url 'landing:contact' %}">Contact</a>
				</li>
			</ul>
		</div>

		<!-- Modal Search -->
		<div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
			<div class="container-search-header">
				<button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
					<img src='{% static "images/icons/icon-close2.png" %}' alt="CLOSE">
				</button>

				{% include "search/form.html" %}
			</div>
		</div>
	</header>
		<!-- messages -->
{% if messages %}
	<div class="container">
        <div class="row">
            <div class="col-sm-12 Am-lr-auto">
                <div class="p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    <div class="message-alert-custom" role="alert">


                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>

                    </div>
                </div>
            </div>
        </div>
	</div>
{% endif %}